# Generated by Django 4.2.6 on 2023-10-23 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('tin_id', models.CharField(max_length=13)),
                ('create_data', models.DateField()),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('address', models.CharField(max_length=255)),
                ('channal', models.CharField(max_length=255)),
                ('detail', models.TextField()),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'district',
            },
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'geography',
            },
        ),
        migrations.CreateModel(
            name='PasswordClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'password_client',
            },
        ),
        migrations.CreateModel(
            name='TypeRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'type_register',
            },
        ),
        migrations.CreateModel(
            name='Subdistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('postcode', models.IntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.district')),
            ],
            options={
                'db_table': 'subdistrict',
            },
        ),
        migrations.CreateModel(
            name='RegisterClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regis_vat', models.BooleanField(default=False)),
                ('date_vat', models.DateField()),
                ('regis_sbt', models.BooleanField(default=False)),
                ('date_sbt', models.DateField()),
                ('regis_sso', models.BooleanField(default=False)),
                ('date_sso', models.DateField()),
                ('regis_e_filling', models.BooleanField(default=False)),
                ('date_e_filling', models.DateField()),
                ('regis_other', models.BooleanField(default=False)),
                ('date_other', models.DateField()),
                ('password_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.passwordclient')),
            ],
            options={
                'db_table': 'register_client',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.country')),
                ('geography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.geography')),
            ],
            options={
                'db_table': 'province',
            },
        ),
        migrations.AddField(
            model_name='passwordclient',
            name='regis_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.typeregister'),
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.province'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('line', models.CharField(max_length=255)),
                ('other', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_address', to='Taskscontroller.client')),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.contact'),
        ),
        migrations.AddField(
            model_name='client',
            name='register_vat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.registerclient'),
        ),
    ]
