# Generated by Django 4.2.6 on 2023-11-28 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, null=True)),
                ('username', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('password', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('confirm_password', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('position', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('permission', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'base_user',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('tax_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('service_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('create_client_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('channal', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('detail', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='ClientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
            ],
            options={
                'db_table': 'client_status',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'district',
            },
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('start_date_service', models.DateTimeField(blank=True, null=True)),
                ('end_date_service', models.DateTimeField(blank=True, null=True)),
                ('start_date_period', models.DateTimeField(blank=True, null=True)),
                ('end_date_period', models.DateTimeField(blank=True, null=True)),
                ('administrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin', to='Taskscontroller.baseuser')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approver', to='Taskscontroller.baseuser')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.client')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewer', to='Taskscontroller.baseuser')),
            ],
            options={
                'db_table': 'engagement',
            },
        ),
        migrations.CreateModel(
            name='EngagementStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'engagement_status',
            },
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'geography',
            },
        ),
        migrations.CreateModel(
            name='RegisterTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('vat_date', models.DateTimeField(blank=True, null=True)),
                ('sbt', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('sbt_date', models.DateTimeField(blank=True, null=True)),
                ('sso', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('sso_date', models.DateTimeField(blank=True, null=True)),
                ('dbd_e_filling', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('dbd_e_filling_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'register_tax',
            },
        ),
        migrations.CreateModel(
            name='RegisterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name_th', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'register_type',
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'task_status',
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'task_type',
            },
        ),
        migrations.CreateModel(
            name='TypeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.category')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.client')),
            ],
            options={
                'db_table': 'type_job',
            },
        ),
        migrations.CreateModel(
            name='TypeJobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('deadline', models.DateTimeField(blank=True, default=None, max_length=255, null=True)),
                ('notification', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_by', to='Taskscontroller.baseuser')),
                ('review_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='review_by', to='Taskscontroller.baseuser')),
                ('type_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.typejob')),
            ],
            options={
                'db_table': 'type_job_detail',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('description', models.TextField()),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.engagement')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.taskstatus')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.tasktype')),
                ('type_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.typejob')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Subdistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('zipcode', models.IntegerField()),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.district')),
            ],
            options={
                'db_table': 'subdistrict',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.country')),
                ('geography', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.geography')),
            ],
            options={
                'db_table': 'province',
            },
        ),
        migrations.AddField(
            model_name='engagement',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.engagementstatus'),
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.province'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('position', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('line', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('other', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.client')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.district')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.province')),
                ('subdistrict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.subdistrict')),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='ClientPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('password', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.client')),
                ('type_password', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.registertype')),
            ],
            options={
                'db_table': 'client_password',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.contact'),
        ),
        migrations.AddField(
            model_name='client',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.district'),
        ),
        migrations.AddField(
            model_name='client',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.province'),
        ),
        migrations.AddField(
            model_name='client',
            name='register_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.registertax'),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.clientstatus'),
        ),
        migrations.AddField(
            model_name='client',
            name='subdistrict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.subdistrict'),
        ),
        migrations.AddField(
            model_name='category',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.engagement'),
        ),
    ]
