# Generated by Django 4.2.6 on 2023-11-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taskscontroller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registertax',
            old_name='dbd',
            new_name='dbd_e_filling',
        ),
        migrations.RenameField(
            model_name='registertax',
            old_name='dbd_date',
            new_name='dbd_e_filling_date',
        ),
        migrations.RenameField(
            model_name='registertax',
            old_name='e_filling',
            new_name='sso',
        ),
        migrations.RenameField(
            model_name='registertax',
            old_name='e_filling_date',
            new_name='sso_date',
        ),
    ]
