# Generated by Django 4.2.6 on 2023-11-09 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Taskscontroller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='same_address_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='same_address_company', to='Taskscontroller.address'),
        ),
    ]
