# Generated by Django 4.2.6 on 2023-11-06 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Taskscontroller', '0002_rename_dbd_registertax_dbd_e_filling_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.AddField(
            model_name='contact',
            name='address1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_address', to='Taskscontroller.address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_address', to='Taskscontroller.address'),
        ),
    ]
