# Generated by Django 4.2.6 on 2023-10-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskscontroller', '0002_alter_client_address_alter_client_channal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='create_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registerclient',
            name='date_e_filling',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registerclient',
            name='date_other',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registerclient',
            name='date_sbt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registerclient',
            name='date_sso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registerclient',
            name='date_vat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registerclient',
            name='regis_e_filling',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='registerclient',
            name='regis_other',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='registerclient',
            name='regis_sbt',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='registerclient',
            name='regis_sso',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='registerclient',
            name='regis_vat',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
