# Generated by Django 4.2.6 on 2023-11-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskscontroller', '0003_alter_client_create_data_alter_client_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerclient',
            name='regis_e_filling',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='registerclient',
            name='regis_other',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='registerclient',
            name='regis_sbt',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='registerclient',
            name='regis_sso',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='registerclient',
            name='regis_vat',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
