# Generated by Django 4.2.6 on 2023-11-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskscontroller', '0004_remove_registertype_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registertype',
            name='short_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
