# Generated by Django 4.2.6 on 2023-11-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taskscontroller', '0004_alter_client_create_client_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='address2',
            new_name='company_address',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='address1',
            new_name='contact_address',
        ),
    ]
