# Generated by Django 4.2.6 on 2023-11-06 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Taskscontroller', '0005_rename_address2_contact_company_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_address',
        ),
        migrations.AddField(
            model_name='client',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.district'),
        ),
        migrations.AddField(
            model_name='client',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.province'),
        ),
        migrations.AddField(
            model_name='client',
            name='subdistrict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.subdistrict'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address0',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_company', to='Taskscontroller.client'),
        ),
        migrations.AddField(
            model_name='contact',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.district'),
        ),
        migrations.AddField(
            model_name='contact',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.province'),
        ),
        migrations.AddField(
            model_name='contact',
            name='subdistrict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.subdistrict'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
