# Generated by Django 4.2.6 on 2023-11-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taskscontroller', '0006_remove_contact_company_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='company_titlename',
        ),
    ]
