# Generated by Django 4.2.6 on 2023-11-10 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Taskscontroller', '0006_passwordclient_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordclient',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskscontroller.passwordclient'),
        ),
    ]
