# Generated by Django 4.2.6 on 2023-11-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskscontroller', '0007_remove_client_company_titlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registertax',
            name='dbd_e_filling',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='registertax',
            name='dbd_e_filling_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registertax',
            name='sbt',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='registertax',
            name='sbt_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registertax',
            name='sso',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='registertax',
            name='sso_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registertax',
            name='vat',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='registertax',
            name='vat_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
